/*
 * ParehNegar.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import LanguageDataContract from './LanguageDataContract';

/**
 * The AddContentWithKeyRequestContract model module.
 * @module model/AddContentWithKeyRequestContract
 * @version 1.0
 */
export default class AddContentWithKeyRequestContract {
  /**
   * Constructs a new <code>AddContentWithKeyRequestContract</code>.
   * @alias module:model/AddContentWithKeyRequestContract
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AddContentWithKeyRequestContract</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AddContentWithKeyRequestContract} obj Optional instance to populate.
   * @return {module:model/AddContentWithKeyRequestContract} The populated <code>AddContentWithKeyRequestContract</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AddContentWithKeyRequestContract();
      if (data.hasOwnProperty('key'))
        obj.key = ApiClient.convertToType(data['key'], 'String');
      if (data.hasOwnProperty('languageData'))
        obj.languageData = ApiClient.convertToType(data['languageData'], [LanguageDataContract]);
    }
    return obj;
  }
}

/**
 * @member {String} key
 */
AddContentWithKeyRequestContract.prototype.key = undefined;

/**
 * @member {Array.<module:model/LanguageDataContract>} languageData
 */
AddContentWithKeyRequestContract.prototype.languageData = undefined;

