/*
 * ParehNegar.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import ContentCategoryContract from './ContentCategoryContract';
import ErrorContract from './ErrorContract';
import SuccessContract from './SuccessContract';

/**
 * The ContentCategoryContractListMessageContract model module.
 * @module model/ContentCategoryContractListMessageContract
 * @version 1.0
 */
export default class ContentCategoryContractListMessageContract {
  /**
   * Constructs a new <code>ContentCategoryContractListMessageContract</code>.
   * @alias module:model/ContentCategoryContractListMessageContract
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ContentCategoryContractListMessageContract</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ContentCategoryContractListMessageContract} obj Optional instance to populate.
   * @return {module:model/ContentCategoryContractListMessageContract} The populated <code>ContentCategoryContractListMessageContract</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ContentCategoryContractListMessageContract();
      if (data.hasOwnProperty('isSuccess'))
        obj.isSuccess = ApiClient.convertToType(data['isSuccess'], 'Boolean');
      if (data.hasOwnProperty('error'))
        obj.error = ErrorContract.constructFromObject(data['error']);
      if (data.hasOwnProperty('success'))
        obj.success = SuccessContract.constructFromObject(data['success']);
      if (data.hasOwnProperty('result'))
        obj.result = ApiClient.convertToType(data['result'], [ContentCategoryContract]);
      if (data.hasOwnProperty('totalCount'))
        obj.totalCount = ApiClient.convertToType(data['totalCount'], 'Number');
      if (data.hasOwnProperty('hasItems'))
        obj.hasItems = ApiClient.convertToType(data['hasItems'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {Boolean} isSuccess
 */
ContentCategoryContractListMessageContract.prototype.isSuccess = undefined;

/**
 * @member {module:model/ErrorContract} error
 */
ContentCategoryContractListMessageContract.prototype.error = undefined;

/**
 * @member {module:model/SuccessContract} success
 */
ContentCategoryContractListMessageContract.prototype.success = undefined;

/**
 * @member {Array.<module:model/ContentCategoryContract>} result
 */
ContentCategoryContractListMessageContract.prototype.result = undefined;

/**
 * @member {Number} totalCount
 */
ContentCategoryContractListMessageContract.prototype.totalCount = undefined;

/**
 * @member {Boolean} hasItems
 */
ContentCategoryContractListMessageContract.prototype.hasItems = undefined;

