/*
 * ParehNegar.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import ContentResponseContract from './ContentResponseContract';

/**
 * The ContentCategoryResponseContract model module.
 * @module model/ContentCategoryResponseContract
 * @version 1.0
 */
export default class ContentCategoryResponseContract {
  /**
   * Constructs a new <code>ContentCategoryResponseContract</code>.
   * @alias module:model/ContentCategoryResponseContract
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ContentCategoryResponseContract</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ContentCategoryResponseContract} obj Optional instance to populate.
   * @return {module:model/ContentCategoryResponseContract} The populated <code>ContentCategoryResponseContract</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ContentCategoryResponseContract();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('key'))
        obj.key = ApiClient.convertToType(data['key'], 'String');
      if (data.hasOwnProperty('contents'))
        obj.contents = ApiClient.convertToType(data['contents'], [ContentResponseContract]);
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
ContentCategoryResponseContract.prototype.id = undefined;

/**
 * @member {String} key
 */
ContentCategoryResponseContract.prototype.key = undefined;

/**
 * @member {Array.<module:model/ContentResponseContract>} contents
 */
ContentCategoryResponseContract.prototype.contents = undefined;

