/*
 * ParehNegar.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import ContentCategoryResponseContract from './ContentCategoryResponseContract';
import LanguageResponseContract from './LanguageResponseContract';

/**
 * The ContentResponseContract model module.
 * @module model/ContentResponseContract
 * @version 1.0
 */
export default class ContentResponseContract {
  /**
   * Constructs a new <code>ContentResponseContract</code>.
   * @alias module:model/ContentResponseContract
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ContentResponseContract</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ContentResponseContract} obj Optional instance to populate.
   * @return {module:model/ContentResponseContract} The populated <code>ContentResponseContract</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ContentResponseContract();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], 'String');
      if (data.hasOwnProperty('languageId'))
        obj.languageId = ApiClient.convertToType(data['languageId'], 'Number');
      if (data.hasOwnProperty('categoryId'))
        obj.categoryId = ApiClient.convertToType(data['categoryId'], 'Number');
      if (data.hasOwnProperty('language'))
        obj.language = LanguageResponseContract.constructFromObject(data['language']);
      if (data.hasOwnProperty('category'))
        obj.category = ContentCategoryResponseContract.constructFromObject(data['category']);
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
ContentResponseContract.prototype.id = undefined;

/**
 * @member {String} data
 */
ContentResponseContract.prototype.data = undefined;

/**
 * @member {Number} languageId
 */
ContentResponseContract.prototype.languageId = undefined;

/**
 * @member {Number} categoryId
 */
ContentResponseContract.prototype.categoryId = undefined;

/**
 * @member {module:model/LanguageResponseContract} language
 */
ContentResponseContract.prototype.language = undefined;

/**
 * @member {module:model/ContentCategoryResponseContract} category
 */
ContentResponseContract.prototype.category = undefined;

