/*
 * ParehNegar.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import ContentCategoryContract from './ContentCategoryContract';
import LanguageContract from './LanguageContract';

/**
 * The ContentContract model module.
 * @module model/ContentContract
 * @version 1.0
 */
export default class ContentContract {
  /**
   * Constructs a new <code>ContentContract</code>.
   * @alias module:model/ContentContract
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ContentContract</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ContentContract} obj Optional instance to populate.
   * @return {module:model/ContentContract} The populated <code>ContentContract</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ContentContract();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('creationDateTime'))
        obj.creationDateTime = ApiClient.convertToType(data['creationDateTime'], 'Date');
      if (data.hasOwnProperty('modificationDateTime'))
        obj.modificationDateTime = ApiClient.convertToType(data['modificationDateTime'], 'Date');
      if (data.hasOwnProperty('isDeleted'))
        obj.isDeleted = ApiClient.convertToType(data['isDeleted'], 'Boolean');
      if (data.hasOwnProperty('deletedDateTime'))
        obj.deletedDateTime = ApiClient.convertToType(data['deletedDateTime'], 'Date');
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], 'String');
      if (data.hasOwnProperty('languageId'))
        obj.languageId = ApiClient.convertToType(data['languageId'], 'Number');
      if (data.hasOwnProperty('categoryId'))
        obj.categoryId = ApiClient.convertToType(data['categoryId'], 'Number');
      if (data.hasOwnProperty('language'))
        obj.language = LanguageContract.constructFromObject(data['language']);
      if (data.hasOwnProperty('category'))
        obj.category = ContentCategoryContract.constructFromObject(data['category']);
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
ContentContract.prototype.id = undefined;

/**
 * @member {Date} creationDateTime
 */
ContentContract.prototype.creationDateTime = undefined;

/**
 * @member {Date} modificationDateTime
 */
ContentContract.prototype.modificationDateTime = undefined;

/**
 * @member {Boolean} isDeleted
 */
ContentContract.prototype.isDeleted = undefined;

/**
 * @member {Date} deletedDateTime
 */
ContentContract.prototype.deletedDateTime = undefined;

/**
 * @member {String} data
 */
ContentContract.prototype.data = undefined;

/**
 * @member {Number} languageId
 */
ContentContract.prototype.languageId = undefined;

/**
 * @member {Number} categoryId
 */
ContentContract.prototype.categoryId = undefined;

/**
 * @member {module:model/LanguageContract} language
 */
ContentContract.prototype.language = undefined;

/**
 * @member {module:model/ContentCategoryContract} category
 */
ContentContract.prototype.category = undefined;

