/*
 * ParehNegar.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import ContentContract from './ContentContract';

/**
 * The ContentCategoryContract model module.
 * @module model/ContentCategoryContract
 * @version 1.0
 */
export default class ContentCategoryContract {
  /**
   * Constructs a new <code>ContentCategoryContract</code>.
   * @alias module:model/ContentCategoryContract
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ContentCategoryContract</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ContentCategoryContract} obj Optional instance to populate.
   * @return {module:model/ContentCategoryContract} The populated <code>ContentCategoryContract</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ContentCategoryContract();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('creationDateTime'))
        obj.creationDateTime = ApiClient.convertToType(data['creationDateTime'], 'Date');
      if (data.hasOwnProperty('modificationDateTime'))
        obj.modificationDateTime = ApiClient.convertToType(data['modificationDateTime'], 'Date');
      if (data.hasOwnProperty('isDeleted'))
        obj.isDeleted = ApiClient.convertToType(data['isDeleted'], 'Boolean');
      if (data.hasOwnProperty('deletedDateTime'))
        obj.deletedDateTime = ApiClient.convertToType(data['deletedDateTime'], 'Date');
      if (data.hasOwnProperty('key'))
        obj.key = ApiClient.convertToType(data['key'], 'String');
      if (data.hasOwnProperty('contents'))
        obj.contents = ApiClient.convertToType(data['contents'], [ContentContract]);
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
ContentCategoryContract.prototype.id = undefined;

/**
 * @member {Date} creationDateTime
 */
ContentCategoryContract.prototype.creationDateTime = undefined;

/**
 * @member {Date} modificationDateTime
 */
ContentCategoryContract.prototype.modificationDateTime = undefined;

/**
 * @member {Boolean} isDeleted
 */
ContentCategoryContract.prototype.isDeleted = undefined;

/**
 * @member {Date} deletedDateTime
 */
ContentCategoryContract.prototype.deletedDateTime = undefined;

/**
 * @member {String} key
 */
ContentCategoryContract.prototype.key = undefined;

/**
 * @member {Array.<module:model/ContentContract>} contents
 */
ContentCategoryContract.prototype.contents = undefined;

