/*
 * ParehNegar.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The DeleteByKeyRequestContract model module.
 * @module model/DeleteByKeyRequestContract
 * @version 1.0
 */
export default class DeleteByKeyRequestContract {
  /**
   * Constructs a new <code>DeleteByKeyRequestContract</code>.
   * @alias module:model/DeleteByKeyRequestContract
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DeleteByKeyRequestContract</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeleteByKeyRequestContract} obj Optional instance to populate.
   * @return {module:model/DeleteByKeyRequestContract} The populated <code>DeleteByKeyRequestContract</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DeleteByKeyRequestContract();
      if (data.hasOwnProperty('key'))
        obj.key = ApiClient.convertToType(data['key'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} key
 */
DeleteByKeyRequestContract.prototype.key = undefined;

