/*
 * ParehNegar.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import FailedReasonType from './FailedReasonType';
import ServiceDetailsContract from './ServiceDetailsContract';
import ValidationContract from './ValidationContract';

/**
 * The ErrorContract model module.
 * @module model/ErrorContract
 * @version 1.0
 */
export default class ErrorContract {
  /**
   * Constructs a new <code>ErrorContract</code>.
   * @alias module:model/ErrorContract
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ErrorContract</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ErrorContract} obj Optional instance to populate.
   * @return {module:model/ErrorContract} The populated <code>ErrorContract</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ErrorContract();
      if (data.hasOwnProperty('validations'))
        obj.validations = ApiClient.convertToType(data['validations'], [ValidationContract]);
      if (data.hasOwnProperty('failedReasonType'))
        obj.failedReasonType = FailedReasonType.constructFromObject(data['failedReasonType']);
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
      if (data.hasOwnProperty('endUserMessage'))
        obj.endUserMessage = ApiClient.convertToType(data['endUserMessage'], 'String');
      if (data.hasOwnProperty('details'))
        obj.details = ApiClient.convertToType(data['details'], 'String');
      if (data.hasOwnProperty('stackTrace'))
        obj.stackTrace = ApiClient.convertToType(data['stackTrace'], ['String']);
      if (data.hasOwnProperty('children'))
        obj.children = ApiClient.convertToType(data['children'], [ErrorContract]);
      if (data.hasOwnProperty('serviceDetails'))
        obj.serviceDetails = ServiceDetailsContract.constructFromObject(data['serviceDetails']);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/ValidationContract>} validations
 */
ErrorContract.prototype.validations = undefined;

/**
 * @member {module:model/FailedReasonType} failedReasonType
 */
ErrorContract.prototype.failedReasonType = undefined;

/**
 * @member {String} message
 */
ErrorContract.prototype.message = undefined;

/**
 * @member {String} endUserMessage
 */
ErrorContract.prototype.endUserMessage = undefined;

/**
 * @member {String} details
 */
ErrorContract.prototype.details = undefined;

/**
 * @member {Array.<String>} stackTrace
 */
ErrorContract.prototype.stackTrace = undefined;

/**
 * @member {Array.<module:model/ErrorContract>} children
 */
ErrorContract.prototype.children = undefined;

/**
 * @member {module:model/ServiceDetailsContract} serviceDetails
 */
ErrorContract.prototype.serviceDetails = undefined;

