/*
 * ParehNegar.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The GetByLanguageRequestContract model module.
 * @module model/GetByLanguageRequestContract
 * @version 1.0
 */
export default class GetByLanguageRequestContract {
  /**
   * Constructs a new <code>GetByLanguageRequestContract</code>.
   * @alias module:model/GetByLanguageRequestContract
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetByLanguageRequestContract</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetByLanguageRequestContract} obj Optional instance to populate.
   * @return {module:model/GetByLanguageRequestContract} The populated <code>GetByLanguageRequestContract</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetByLanguageRequestContract();
      if (data.hasOwnProperty('language'))
        obj.language = ApiClient.convertToType(data['language'], 'String');
      if (data.hasOwnProperty('key'))
        obj.key = ApiClient.convertToType(data['key'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} language
 */
GetByLanguageRequestContract.prototype.language = undefined;

/**
 * @member {String} key
 */
GetByLanguageRequestContract.prototype.key = undefined;

