/*
 * ParehNegar.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The LanguageResponseContract model module.
 * @module model/LanguageResponseContract
 * @version 1.0
 */
export default class LanguageResponseContract {
  /**
   * Constructs a new <code>LanguageResponseContract</code>.
   * @alias module:model/LanguageResponseContract
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>LanguageResponseContract</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LanguageResponseContract} obj Optional instance to populate.
   * @return {module:model/LanguageResponseContract} The populated <code>LanguageResponseContract</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LanguageResponseContract();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
LanguageResponseContract.prototype.id = undefined;

/**
 * @member {String} name
 */
LanguageResponseContract.prototype.name = undefined;

