/*
 * ParehNegar.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The LanguageDataContract model module.
 * @module model/LanguageDataContract
 * @version 1.0
 */
export default class LanguageDataContract {
  /**
   * Constructs a new <code>LanguageDataContract</code>.
   * @alias module:model/LanguageDataContract
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>LanguageDataContract</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LanguageDataContract} obj Optional instance to populate.
   * @return {module:model/LanguageDataContract} The populated <code>LanguageDataContract</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LanguageDataContract();
      if (data.hasOwnProperty('language'))
        obj.language = ApiClient.convertToType(data['language'], 'String');
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} language
 */
LanguageDataContract.prototype.language = undefined;

/**
 * @member {String} data
 */
LanguageDataContract.prototype.data = undefined;

