/*
 * ParehNegar.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import ErrorContract from './ErrorContract';
import SuccessContract from './SuccessContract';

/**
 * The MessageContract model module.
 * @module model/MessageContract
 * @version 1.0
 */
export default class MessageContract {
  /**
   * Constructs a new <code>MessageContract</code>.
   * @alias module:model/MessageContract
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MessageContract</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MessageContract} obj Optional instance to populate.
   * @return {module:model/MessageContract} The populated <code>MessageContract</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MessageContract();
      if (data.hasOwnProperty('isSuccess'))
        obj.isSuccess = ApiClient.convertToType(data['isSuccess'], 'Boolean');
      if (data.hasOwnProperty('error'))
        obj.error = ErrorContract.constructFromObject(data['error']);
      if (data.hasOwnProperty('success'))
        obj.success = SuccessContract.constructFromObject(data['success']);
    }
    return obj;
  }
}

/**
 * @member {Boolean} isSuccess
 */
MessageContract.prototype.isSuccess = undefined;

/**
 * @member {module:model/ErrorContract} error
 */
MessageContract.prototype.error = undefined;

/**
 * @member {module:model/SuccessContract} success
 */
MessageContract.prototype.success = undefined;

