/*
 * ParehNegar.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ServiceDetailsContract model module.
 * @module model/ServiceDetailsContract
 * @version 1.0
 */
export default class ServiceDetailsContract {
  /**
   * Constructs a new <code>ServiceDetailsContract</code>.
   * @alias module:model/ServiceDetailsContract
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ServiceDetailsContract</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ServiceDetailsContract} obj Optional instance to populate.
   * @return {module:model/ServiceDetailsContract} The populated <code>ServiceDetailsContract</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ServiceDetailsContract();
      if (data.hasOwnProperty('serviceRouteAddress'))
        obj.serviceRouteAddress = ApiClient.convertToType(data['serviceRouteAddress'], 'String');
      if (data.hasOwnProperty('methodName'))
        obj.methodName = ApiClient.convertToType(data['methodName'], 'String');
      if (data.hasOwnProperty('path'))
        obj.path = ApiClient.convertToType(data['path'], 'String');
      if (data.hasOwnProperty('projectName'))
        obj.projectName = ApiClient.convertToType(data['projectName'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} serviceRouteAddress
 */
ServiceDetailsContract.prototype.serviceRouteAddress = undefined;

/**
 * @member {String} methodName
 */
ServiceDetailsContract.prototype.methodName = undefined;

/**
 * @member {String} path
 */
ServiceDetailsContract.prototype.path = undefined;

/**
 * @member {String} projectName
 */
ServiceDetailsContract.prototype.projectName = undefined;

