/*
 * ParehNegar.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The SuccessContract model module.
 * @module model/SuccessContract
 * @version 1.0
 */
export default class SuccessContract {
  /**
   * Constructs a new <code>SuccessContract</code>.
   * @alias module:model/SuccessContract
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SuccessContract</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SuccessContract} obj Optional instance to populate.
   * @return {module:model/SuccessContract} The populated <code>SuccessContract</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SuccessContract();
      if (data.hasOwnProperty('endUserMessage'))
        obj.endUserMessage = ApiClient.convertToType(data['endUserMessage'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} endUserMessage
 */
SuccessContract.prototype.endUserMessage = undefined;

