/*
 * ParehNegar.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ParehNegarwebApi);
  }
}(this, function(expect, ParehNegarwebApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ParehNegarwebApi.ContentApi();
  });

  describe('(package)', function() {
    describe('ContentApi', function() {
      describe('apiContentAddBulkContentWithKeyPost', function() {
        it('should call apiContentAddBulkContentWithKeyPost successfully', function(done) {
          // TODO: uncomment, update parameter values for apiContentAddBulkContentWithKeyPost call and complete the assertions
          /*
          var opts = {};

          instance.apiContentAddBulkContentWithKeyPost(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ParehNegarwebApi.MessageContract);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiContentAddContentWithKeyPost', function() {
        it('should call apiContentAddContentWithKeyPost successfully', function(done) {
          // TODO: uncomment, update parameter values for apiContentAddContentWithKeyPost call and complete the assertions
          /*
          var opts = {};

          instance.apiContentAddContentWithKeyPost(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ParehNegarwebApi.MessageContract);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiContentDeleteByKeyPost', function() {
        it('should call apiContentDeleteByKeyPost successfully', function(done) {
          // TODO: uncomment, update parameter values for apiContentDeleteByKeyPost call and complete the assertions
          /*
          var opts = {};

          instance.apiContentDeleteByKeyPost(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ParehNegarwebApi.MessageContract);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiContentGetByLanguagePost', function() {
        it('should call apiContentGetByLanguagePost successfully', function(done) {
          // TODO: uncomment, update parameter values for apiContentGetByLanguagePost call and complete the assertions
          /*
          var opts = {};

          instance.apiContentGetByLanguagePost(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ParehNegarwebApi.ContentResponseContractMessageContract);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
