/*
 * ParehNegar.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ParehNegarwebApi);
  }
}(this, function(expect, ParehNegarwebApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ErrorContract', function() {
      beforeEach(function() {
        instance = new ParehNegarwebApi.ErrorContract();
      });

      it('should create an instance of ErrorContract', function() {
        // TODO: update the code to test ErrorContract
        expect(instance).to.be.a(ParehNegarwebApi.ErrorContract);
      });

      it('should have the property validations (base name: "validations")', function() {
        // TODO: update the code to test the property validations
        expect(instance).to.have.property('validations');
        // expect(instance.validations).to.be(expectedValueLiteral);
      });

      it('should have the property failedReasonType (base name: "failedReasonType")', function() {
        // TODO: update the code to test the property failedReasonType
        expect(instance).to.have.property('failedReasonType');
        // expect(instance.failedReasonType).to.be(expectedValueLiteral);
      });

      it('should have the property message (base name: "message")', function() {
        // TODO: update the code to test the property message
        expect(instance).to.have.property('message');
        // expect(instance.message).to.be(expectedValueLiteral);
      });

      it('should have the property endUserMessage (base name: "endUserMessage")', function() {
        // TODO: update the code to test the property endUserMessage
        expect(instance).to.have.property('endUserMessage');
        // expect(instance.endUserMessage).to.be(expectedValueLiteral);
      });

      it('should have the property details (base name: "details")', function() {
        // TODO: update the code to test the property details
        expect(instance).to.have.property('details');
        // expect(instance.details).to.be(expectedValueLiteral);
      });

      it('should have the property stackTrace (base name: "stackTrace")', function() {
        // TODO: update the code to test the property stackTrace
        expect(instance).to.have.property('stackTrace');
        // expect(instance.stackTrace).to.be(expectedValueLiteral);
      });

      it('should have the property children (base name: "children")', function() {
        // TODO: update the code to test the property children
        expect(instance).to.have.property('children');
        // expect(instance.children).to.be(expectedValueLiteral);
      });

      it('should have the property serviceDetails (base name: "serviceDetails")', function() {
        // TODO: update the code to test the property serviceDetails
        expect(instance).to.have.property('serviceDetails');
        // expect(instance.serviceDetails).to.be(expectedValueLiteral);
      });

    });
  });

}));
