/*
 * ParehNegar.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ParehNegarwebApi);
  }
}(this, function(expect, ParehNegarwebApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('GetByLanguageRequestContract', function() {
      beforeEach(function() {
        instance = new ParehNegarwebApi.GetByLanguageRequestContract();
      });

      it('should create an instance of GetByLanguageRequestContract', function() {
        // TODO: update the code to test GetByLanguageRequestContract
        expect(instance).to.be.a(ParehNegarwebApi.GetByLanguageRequestContract);
      });

      it('should have the property language (base name: "language")', function() {
        // TODO: update the code to test the property language
        expect(instance).to.have.property('language');
        // expect(instance.language).to.be(expectedValueLiteral);
      });

      it('should have the property key (base name: "key")', function() {
        // TODO: update the code to test the property key
        expect(instance).to.have.property('key');
        // expect(instance.key).to.be(expectedValueLiteral);
      });

    });
  });

}));
